# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'

    - name: Build
      run: go build -v ./...

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        skip-cache: 'true'
  
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged 
        ports: 
          - 2375:2375
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: go test -v --cover ./...


